using UnityEngine;

namespace Fy.EventSystem.Examples
{
    /// <summary>
    /// Example publisher: invokes a <see cref="PlayerScoredEvent"/> through the generated call-site API.
    /// Click the on-screen button while in play mode to score.
    /// </summary>
    public sealed class ScorePublisher : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("Points awarded per score.")]
        private int _pointsPerScore = 10;

        private int _totalScore;

        private void OnGUI()
        {
            if (!GUILayout.Button("Score!", GUILayout.Width(120f), GUILayout.Height(40f)))
            {
                return;
            }

            _totalScore += _pointsPerScore;

            // Generated by the source generator: forwards to the IEventService resolved from the ServiceLocator.
            bool invoked = new PlayerScoredEvent(_pointsPerScore, _totalScore).Invoke(this);

            Debug.Log($"[Publisher] Scored {_pointsPerScore} (total {_totalScore}). " +
                      $"Invoke reached a listener: {invoked}.", this);
        }
    }
}
