using UnityEngine;

namespace Fy.EventSystem.Examples
{
    /// <summary>
    /// Example listener: subscribes on enable through the generated call-site API, reacts to every
    /// <see cref="PlayerScoredEvent"/>, and unsubscribes on disable using the returned <see cref="EventHandle"/>.
    /// </summary>
    public sealed class ScoreListener : MonoBehaviour
    {
        private EventHandle _handle;

        private void OnEnable()
        {
            // Generated by the source generator: forwards to the IEventService resolved from the ServiceLocator.
            _handle = PlayerScoredEvent.AddListener(HandlePlayerScored);
        }

        private void OnDisable()
        {
            // Removes through the service that created the handle, and is safe once that service is gone.
            _handle.RemoveListener();
        }

        // The event data arrives by readonly reference alongside the invocation context.
        private void HandlePlayerScored(ref EventContext context, in PlayerScoredEvent e)
        {
            Debug.Log($"[Listener] Reacted: +{e.Points} points, total is now {e.TotalScore}. " +
                      $"Sender was '{context.Sender}'.", this);
        }
    }
}
